services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      BACKEND_URL: http://backend:8080
      NEXT_PUBLIC_API_URL: http://localhost:8080
